### ISSUE TITLE
Evolution/Devolution scripts

### ISSUE THREAD

**Issue by MatthewMeacham** [MatthewMeacham/HomeworkOrganizer#17]
Rewrite the SQL scripts, this will be an ongoing thing once we go into production and so I want someone to learn the SQL evolution stuff, we need to stop having it auto-generate that stuff for us, it will be safer this way in production. The salt for example is stored as a varchar(255) when it is a fixed 64 character String, so it could be stored as a char(64).

**Comment by hwaldstein** [comment]
I've got custom DB evolutions scripts set up. Now, I just need to figure out what each data type should look like, then changing everything will be a piece of cake. I've got MySQL running on my dev machine because Jim didn't seem to like the idea of using AWS's DB.

**Comment by hwaldstein** [comment]
These are doable, and actually would be a piece of cake. Let me know what and when you'd like the changes, and I can walk you through exactly what needs to happen. Essentially, you just need to put your SQL into the evolutions folder. @MatthewMeacham
