### ISSUE TITLE
More Assignment types

### ISSUE THREAD

**Issue by MatthewMeacham** [MatthewMeacham/HomeworkOrganizer#18]
Think of more kinds of assignments we can add, then add them into Application.OPTIONS

**Comment by hwaldstein** [comment]
I'm pretty happy with the amount of assignments that we've got currently. I don't want to kill our users with options.

**Comment by hwaldstein** [comment]
@MatthewMeacham If you're okay with it, I'm going to close with issue. Let me know otherwise.
