### ISSUE TITLE
Editing Classes

### ISSUE THREAD

**Issue by mpowell14** [MatthewMeacham/HomeworkOrganizer#44]
![image](https://cloud.githubusercontent.com/assets/10621212/8875909/e0c74522-31e1-11e5-9fc7-248cd7221a2b.png)

When I try to edit a class, I get this error.

**Comment by MatthewMeacham** [comment]
This is fixed in my latest code, have yet to push.

**Comment by mpowell14** [comment]
Keep issues open until they're fixed on the live site.
