### ISSUE TITLE
Security Checks and Composition

### ISSUE THREAD

**Issue by MatthewMeacham** [MatthewMeacham/HomeworkOrganizer#6]
Finish the security implementation that keeps users from being able to access someone else's page and if they try, make them log in

**Comment by hwaldstein** [comment]
I'm currently finding it difficult to write this code. I'm not as familiar with the application as you are, @MatthewMeacham, so I'd prefer if you took point on this issue. I've got a couple of repos with trivial implementations of this in my personal GETHIP repos, but this would require making lots of changes to Orgnizer that I'm more comfortable with you doing, Matthew. So, I can consult with specific issues. But, I'd prefer if you too point on this.
